### ISSUE TITLE
Empty mvt's at zoom levels 15 and up

### ISSUE THREAD

**Issue by mngyng** [NYCPlanning/geojson2mvt#4]
Maybe an issue with default setting of geojson-vt. Used your example but end up with all mvt's having file size 0 from z=15 and up.

**Comment by hanbyul-here** [comment]
Having same issue 🖐  (I used my own data)

**Comment by hanbyul-here** [comment]
Hi again! 

I could have time to play with this problem. I could solve this problem by passing the options that geojson-vt requires to pre-generate all the requested tiles (https://github.com/mapbox/geojson-vt#options). You can see my solution [here](https://github.com/hanbyul-here/geojson2mvt/blob/master/src/index.js#L9-L13). 

I can make a PR if NYCPlanning team is fine with this solution!

**Comment by chriswhong** [comment]
Hi @hanbyul-here, we would love a pull request!  Thanks for pointing this out.

**Comment by chriswhong** [comment]
Closed by #5
