### ISSUE TITLE
Multiple layers

### ISSUE THREAD

**Issue by ahocevar** [NYCPlanning/geojson2mvt#8]
Would you be open to accepting a pull request that changes the API slightly to support multiple layers? Something like
```js
var fs = require('fs');
var geojson2mvt = require('geojson2mvt');
 
const busRoutes = './bus_routes.geojson';
const busStops = './bus_stops.geojson';
 
var options = {
  rootDir: 'tiles',
  bbox : [40.426042,-74.599228,40.884448,-73.409958], //[south,west,north,east]
  zoom : {
    min : 8,
    max : 18,
  },
  layers: {
    'layer0': JSON.parse(fs.readFileSync(busRoutes, "utf8")),
    'layer1': JSON.parse(fs.readFileSync(busStops, "utf8"))
  },
};
 
// build the static tile pyramid
geojson2mvt(options);
```
I could also make this in a backwards compatible way, if desired.

**Comment by benstadin** [comment]
I'd be interested in this feature. I was just looking for it ;). Could you share your changes, or create a fork?

**Comment by ahocevar** [comment]
Cool, thanks! I have not implemented it yet, but I am on it now and will send a pull request soon.

**Comment by ahocevar** [comment]
I just submitted pull request #9, which implements support for multiple layers. Backwards compatibility is maintained.

**Comment by ahocevar** [comment]
@benstadin, did you get a chance to look at my pull request #9?
